"""обавление новых колонок для настроений

Revision ID: 0150517042a2
Revises: 
Create Date: 2025-02-23 19:26:19.910806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0150517042a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('morning_mood', sa.String(length=10), nullable=True),
    sa.Column('afternoon_mood', sa.String(length=10), nullable=True),
    sa.Column('evening_mood', sa.String(length=10), nullable=True),
    sa.Column('night_mood', sa.String(length=10), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Entry')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Entry',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('mood', sa.VARCHAR(length=10), nullable=False),
    sa.Column('time_of_day', sa.VARCHAR(length=20), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('entry')
    op.drop_table('user')
    # ### end Alembic commands ###
